import { useBooking } from '../booking/BookingContext.jsx'

export function Hero({ venue }) {
  const hasPhoto = Boolean(venue.hero?.image)
  const { setOpen: setBookingOpen } = useBooking()

  return (
    <section
      id="top"
      className={`hero${hasPhoto ? ' hero--photo' : ' hero--paint'}`}
      aria-label="Welcome"
    >
      <div className="hero__content">
        <h1 className="hero__name hero__reveal">{venue.name}</h1>
        {venue.subtitle || venue.place ? (
          <p className="hero__place hero__reveal">
            {[venue.subtitle, venue.place].filter(Boolean).join(' · ')}
          </p>
        ) : null}
        <div className="hero__actions hero__reveal">
          <button type="button" className="btn btn--on-hero" onClick={() => setBookingOpen(true)}>
            Book a table
          </button>
        </div>
      </div>

      {hasPhoto ? (
        <div className="hero__media">
          <div className="hero__stage">
            {/* The facade is the LCP element, so it carries fetchPriority
                and stays eager. Variants are generated by
                scripts/optimize-images.mjs — WebP first, palette PNG as the
                fallback because the artwork needs its alpha channel. */}
            <div className="hero__facade" aria-hidden="true">
              <picture>
                <source
                  type="image/webp"
                  srcSet="/images/hero-736.webp 736w, /images/hero-1104.webp 1104w, /images/hero-1463.webp 1463w"
                  sizes="(min-width: 900px) 46vw, 92vw"
                />
                <img
                  src="/images/hero-736.png"
                  srcSet="/images/hero-736.png 736w, /images/hero-1104.png 1104w, /images/hero-1463.png 1463w"
                  sizes="(min-width: 900px) 46vw, 92vw"
                  alt=""
                  width="1463"
                  height="1280"
                  fetchPriority="high"
                />
              </picture>
            </div>
            <p className="hero__tagline hero__tagline--under hero__reveal">{venue.hero.caption}</p>
          </div>
          <div className="hero__veil" aria-hidden="true" />
        </div>
      ) : (
        <p className="hero__tagline hero__reveal">{venue.tagline}</p>
      )}
    </section>
  )
}
